from dotenv import load_dotenv
import os

load_dotenv()

# CONSUMPTION

CONSUMPTION_DATABASE_CONNECTION_STRING = os.getenv("CONSUMPTION_DATABASE_CONNECTION_STRING")

# UNIVERSAL

KAFKA_BROKER = os.getenv("KAFKA_BROKER")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
