from dotenv import load_dotenv
import os

load_dotenv()

# CONSUMPTION

CONSUMPTION_DATABASE_URL = os.getenv("CONSUMPTION_DATABASE_URL")
CONSUMPTION_DATABASE_USER = os.getenv("CONSUMPTION_DATABASE_USER")
CONSUMPTION_DATABASE_PASSWORD = os.getenv("CONSUMPTION_DATABASE_PASSWORD")

# UNIVERSAL

KAFKA_BROKER = os.getenv("KAFKA_BROKER")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
